### PR TITLE
Depend on "util" module instead of the deprecated "sys"

### PR DESCRIPTION
**Pull request by ikr**
Otherwise, when using node-imagemagick in an application running on node 0.8, I'm getting:

```
~$ node Sites/myapp.ikr.xiag.ch/nodes/img/app.js 

sys.js:1
throw new Error(
      ^
Error: The "sys" module is now called "util".
    at sys.js:1:69
    at NativeModule.compile (node.js:602:5)
    at Function.NativeModule.require (node.js:570:18)
    at Function.Module._load (module.js:297:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Users/ikr/Sites/myapp.ikr.xiag.ch/nodes/img/node_modules/imagemagick/imagemagick.js:1:73)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
```

### CODE REVIEW

**Comment by davidmurdoch** [comment]
Please pull this in soon.

**Comment by heldr** [comment]
+1

**Comment by tiratatp** [comment]
+1

**Comment by nherment** [comment]
+1

**Comment by davidmurdoch** [comment]
This was "fixed" in node 0.8.1 https://github.com/joyent/node/commit/f2a9ed487369ab7222522e1097708550adbe165c

**Comment by newbyca** [comment]
+1

**Comment by glesperance** [comment]
+1

**Comment by rsms** [comment]
Fixed in 34c8deb

**Pull request closed without merging**
