### PR TITLE
Allow passing process options into convert, not just timeout

### PR DESCRIPTION
**Pull request by abram**
I need to handle cases where the output image from convert() is greater than 500K, which means passing in a larger maxBuffer value. This change makes it possible to pass an options object with maxBuffer and/or timeout to convert().

### CODE REVIEW

**Comment by thiagoarrais** [comment]
+1

(I have already pulled this into my branch)

**Comment by gijsk** [comment]
+1, I'm also using a similar fix.

**Comment by gijsk** [comment]
By the way, @abram, did you fix the consumers (exports.resizeCall and friends)?

**Comment by abram** [comment]
I designed it to be backwards compatible. I've been thinking about this some more though, and i think the right approach is to avoid putting all the data in a Buffer and use streams instead. That's the right way to gracefully deal with large files.

Does that sound like a better approach to you guys?

**Comment by thiagoarrais** [comment]
Maybe I'm misunderstanding here. But isn't this already supported in convert both for input and output?

This code works for me:

```
var im = require('imagemagick'),
    fs = require('fs');

conv = im.convert(['-resize', '640x', '-', '/tmp/kitten-640.jpg'])
output = fs.createWriteStream('/tmp/kitten-640.jpg');
input = fs.createReadStream('/tmp/kitten.jpg');
conv.on('data', function(chunk) { output.write(chunk, 'binary'); });
conv.on('end', function() { output.end(); } );
input.on('data', function(chunk) { conv.stdin.write(chunk, null); });
input.on('end', function() { conv.stdin.end(); });
```

Is this what you're talking about?

**Comment by abram** [comment]
Heh, that does look like exactly what I'm looking for. Somehow I missed that
it was possible to do that. I'll switch to using streams, which should
eliminate the need to increase the max buffer size.

Thanks!

-Abe

**Comment by thiagoarrais** [comment]
Rasmus, I think it is ok to close this pull request. Isn't it, abram?

**Comment by abram** [comment]
Yep, fine with me.

**Comment by greggreenhaw** [comment]
Why was this fix never implemented it is ridiculous that you can not increase the max buffer size as a resizeArgs or via convert directly.

**Pull request closed without merging**
