### PR TITLE
Made a few changes so that you don't have to write to file for cropping

### PR DESCRIPTION
**Pull request by jteplitz**
I made it so that crop now accepts srcData instead of a srcPath, and won't through an error if you don't send a dstPath, because that way you can send the resulting image to stdout.

### CODE REVIEW

**Comment by jteplitz** [comment]
Sorry some console logs leaked through there that I forgot to delete.

**Comment by jhnlsn** [comment]
Exactly what I was looking for, thanks.

**Comment by jhnlsn** [comment]
I'm guessing this package is no longer supported maintained?  Possible you could hand this off to someone else?

**Comment by ghost** [comment]
Agree, would be nice if someone could take over and further improve this useful package.

**Comment by jteplitz** [comment]
Definitely, it's a really nice package and doesn't look like it's been maintained in a while.

**Comment by ghost** [comment]
@jteplitz602

Just wondering did you fork this package? If not could you do so and share?

**Comment by jteplitz** [comment]
Yep I did: https://github.com/jteplitz602/node-imagemagick

**Comment by ghost** [comment]
Cool, thanks.

**Comment by jteplitz** [comment]
No problem. I've also reached out to rsms on twitter to see if he still plans on maintaing this repo.

**Comment by jhnlsn** [comment]
@bardu for future reference, jteplitz602 added a pull request to this ticket as you can see from those 2 commit's above.  You are always able to grab the code from there or just use that repo instead of this one if the author never accepts the pull request.  As in the case of this repo :)

**Comment by rsms** [comment]
Thanks for being patient guys

**Comment by jhnlsn** [comment]
thank you!

**Pull request merged**
