### PR TITLE
removed sys = require("sys")

### PR DESCRIPTION
**Pull request by marcbaechinger**
Hi

one of my scripts has a dependency to your node-imagemagick module. When trying to use again I found that it didn't work anymore because there is a require("sys") statement which causes an error. 'sys' has been moved to 'util' for recent node versions.

Anyway, the sys variable is not used anymore in node-imagemagick an hence can simply be removed as I did it for my local installation of it. 

Removing it from the repo of node-imagemagick would make node-csssprite work again out-of-the-box with a npm i -g node-imagemagick. So I kindly ask you to pull that change into. :-)

Anyway, many thanks for node-imagemagick which made my work a snap.

cheers
marc

### CODE REVIEW

**Comment by jnak** [comment]
+1

**Comment by defvol** [comment]
npm package still have it!

├── imagemagick@0.1.2

HackBook:gmx Rod$ grep -R "require.*sys" \* 
node_modules/imagemagick/imagemagick.js:var sys = require('sys'),
node_modules/imagemagick/test-crop.js:var sys = require('sys'),
node_modules/imagemagick/test.js:var sys = require('sys'),

**Comment by dharFr** [comment]
+1

**Comment by laufzeit** [comment]
+1

**Comment by tomasikp** [comment]
didn't #30 solve this?

**Comment by dharFr** [comment]
Yes it does, but as @wilhelmbot noticed, the last version on npm registry (0.1.2) is not up to date with the repository.

**Comment by domenic** [comment]
Can you publish a new version to npm? Trying to get ready for the incoming Node 0.8...

**Comment by wavded** [comment]
+1 @rsms could you publish a new one?

**Comment by wavded** [comment]
actually i just ported over to https://github.com/aheckmann/gm, was pretty simple to do so (has an imagemagick wrapper as well) if anyone is interested

**Comment by domenic** [comment]
@wavded Nice find; I like the built-in streaming support.

**Pull request merged**
