### PR TITLE
Add Montage Support

### PR DESCRIPTION
**Pull request by enobrev**
Added a simple interface to the [montage](http://www.imagemagick.org/script/montage.php) command (same as the existing convert implementation).

### CODE REVIEW

**Comment by xcambar** [comment]
Please merge or explain...

**Comment by rsms** [comment]
"enobrev closed the pull request"

**Comment by ming-codes** [comment]
It's closed. Was it not merged?

**Comment by SamDecrock** [comment]
no, it was not.
Montage is still missing from this module

**Pull request closed without merging**
